name: ms-front-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install with npm
        run: npm install
      - name: Build with npm
        run: npm run build
      - name: Docker buid
        run: docker build -t $GITHUB_REPOSITORY:$GITHUB_SHA ./
      - name: Docker tag
        run: docker tag $GITHUB_REPOSITORY:$GITHUB_SHA registry.cn-zhangjiakou.aliyuncs.com/rent-zz/rent:ms-front-$GITHUB_SHA
      - name: Login with Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username="${{ secrets.DOCKER_USERNAME }}" --password-stdin registry.cn-zhangjiakou.aliyuncs.com
      - name: Push image to registry
        run: docker push registry.cn-zhangjiakou.aliyuncs.com/rent-zz/rent:ms-front-$GITHUB_SHA
      - name: Docker tag remote latest
        run: docker tag $GITHUB_REPOSITORY:$GITHUB_SHA registry.cn-zhangjiakou.aliyuncs.com/rent-zz/rent:ms-front-latest
      - name: Push image to registry
        run: docker push registry.cn-zhangjiakou.aliyuncs.com/rent-zz/rent:ms-front-latest
